### ISSUE TITLE
Schema suggestions

### ISSUE THREAD

**Issue by brtrick** [huangs2022672/depth-of-field#2]
Well done again! A few comments:
1. You don't need to store an image_url for photos in your db (but you will want it in your state). We will use AWS and ActiveStorage to handle that. 
2. Flickr allows a single photo to be stored in multiple albums, so better to use a joins table.
3. Don't think you need album_id in comments table. (Unless you want to allow comments on albums--not sure if Flickr does that--in which case you should make the commentable item a polymorphic field.)
4. Use a polymorphic field for your likes and tags. (These are bonus items.)
5. In bullet points after each table, specify what table the table's various foreign keys reference.

**Comment by brtrick** [comment]
Also, looks like Flickr requires a user to enter their age when signing up, so probably want to store that as well.

**Comment by huangs2022672** [comment]
1. image_url removed from photos table
2. added a joins table (could use a better name) to the bonus section
3. removed album_id from comments table, since album is going to be a bonus now.
4. likes and tags have been downgraded, only photos get likes and tags now (flickr calls likes "faves", not sure if it's important enough to change that when I start FSP)
5. made sure each foreign key has a reference
6. age added to user's table

question: if I wanted to assign a new user a random image as a profile pic and allow them to update it later, should I add this as a column for the users table?? would it be a image_url??

other: I've updated MVP list per our Slack conversation, please take a look when you have time, and thanks for all the feedback!!!!

**Comment by brtrick** [comment]
Looks good. Closing.
